import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Common/Header";
import Footer from "./Common/Footer";
import ScrollToTop from "./Components/ScrolltoTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); 

export const metadata = {
  title: "Monsta--The Official Site for Monsta Studios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <ScrollToTop/>
        <Footer/>
      </body>
    </html>
  );
}
